export interface IconItem {
  id: string;
  name: string;
  figmaNodeId: string;
}

/** Базовый размер иконки в каталоге Wilhelm Icons (px). */
export const ICON_DEFAULT_SIZE = 24;

export function formatIconDefaultSize(size = ICON_DEFAULT_SIZE): string {
  return `${size}×${size}`;
}

export interface IconSection {
  id: string;
  title: string;
  items: IconItem[];
}

function icon(id: string, name: string, figmaNodeId: string): IconItem {
  return { id, name, figmaNodeId };
}

/** Каталог иконок Wilhelm Icons — категории и node id из Figma. */
export const iconSections: IconSection[] = [
  {
    id: 'alternative',
    title: 'Alternative',
    items: [
      icon('mastercard', 'mastercard', '0:105'),
      icon('qiwi', 'qiwi', '0:114'),
      icon('visa', 'visa', '0:121'),
      icon('shell', 'shell', '1517:185'),
      icon('bp', 'bp', '1517:186'),
      icon('rosneft', 'rosneft', '1517:199'),
      icon('neftmagistral', 'neftmagistral', '1518:0'),
      icon('surge', 'surge', '0:98'),
      icon('plus_mini', 'plus_mini', '0:96'),
      icon('more', 'more', '0:89'),
      icon('spinner', 'spinner', '1711:8'),
      icon('hexagon', 'hexagon', '1976:5'),
    ],
  },
  {
    id: 'action',
    title: 'Action',
    items: [
      icon('camera', 'camera', '696:979'),
      icon('date', 'date', '0:243'),
      icon('dots', 'dots', '0:259'),
      icon('edit', 'edit', '0:266'),
      icon('filter_outline', 'filter_outline', '0:283'),
      icon('filter_solid', 'filter_solid', '0:293'),
      icon('layers', 'layers', '0:329'),
      icon('location', 'location', '0:335'),
      icon('microphone', 'microphone', '0:350'),
      icon('order_mode', 'order_mode', '0:375'),
      icon('phone', 'phone', '0:398'),
      icon('scan_card', 'scan_card', '0:455'),
      icon('search', 'search', '0:463'),
      icon('radar', 'radar', '88:38'),
      icon('settings', 'settings', '693:928'),
      icon('star', 'star', '0:489'),
      icon('star_outline', 'star_outline', '0:493'),
      icon('stop', 'stop', '111:3'),
      icon('thumb_down', 'thumb_down', '0:499'),
      icon('thumb_up', 'thumb_up', '0:505'),
      icon('send', 'send', '0:469'),
      icon('navigation', 'navigation', '0:360'),
      icon('copy', 'copy', '1419:18'),
      icon('trash', 'trash', '210:22'),
      icon('logout', 'logout', '696:977'),
      icon('my_location', 'my_location', '2342:6'),
      icon('my_location_active', 'my_location_active', '2342:11'),
      icon('route', 'route', '2484:21'),
      icon('compass', 'compass', '3112:41'),
    ],
  },
  {
    id: 'informative',
    title: 'Informative',
    items: [
      icon('pin_dot', 'pin_dot', '0:406'),
      icon('point_dot', 'point/dot', '448:20'),
      icon('pin_dot_big', 'pin_dot_big', '233:13'),
      icon('timer', 'timer', '0:519'),
      icon('time_round', 'time_round', '151:19'),
      icon('person_solid', 'person_solid', '0:391'),
      icon('person_outline', 'person_outline', '0:383'),
      icon('ban', 'ban', '0:165'),
      icon('star_round', 'star_round', '477:23'),
      icon('store', 'store', '789:923'),
      icon('logo_round', 'logo_round', '553:17'),
      icon('lock', 'lock', '579:2'),
      icon('friends', 'friends', '645:25'),
      icon('food', 'food', '929:1'),
      icon('grocery', 'grocery', '929:2'),
      icon('box', 'box', '929:3'),
      icon('notification', 'Notification', '1155:937'),
      icon('pin_mini', 'pin_mini', '1188:13'),
      icon('box_mini', 'box_mini', '1188:0'),
      icon('car', 'car', '1188:42'),
      icon('flag', 'flag', '1188:50'),
      icon('disadvantageously', 'disadvantageously', '1228:30'),
      icon('order_in_the_back', 'order_in_the_back', '1228:58'),
      icon('traffic', 'traffic', '1228:94'),
      icon('badboy', 'badboy', '1228:112'),
      icon('police', 'police', '1228:120'),
      icon('waiting', 'waiting', '1228:138'),
      icon('breaking', 'breaking', '1228:153'),
      icon('walking', 'walking', '1301:19'),
      icon('chain', 'chain', '1350:24'),
      icon('best_order', 'best_order', '1350:32'),
      icon('switch', 'switch', '1669:2'),
      icon('tariff', 'tariff', '1739:0'),
      icon('in_time', 'in_time', '1740:10'),
      icon('no_parking', 'no_parking', '1773:11'),
      icon('menu', 'menu', '1905:21'),
      icon('crash', 'crash', '2027:125'),
      icon('roadworks', 'roadworks', '2027:126'),
      icon('geominimal', 'geominimal', '2078:317'),
      icon('briefcase', 'briefcase', '2338:391'),
      icon('businessman', 'businessman', '2422:62'),
      icon('newspaper', 'newspaper', '2436:95'),
      icon('motivation', 'motivation', '2532:2'),
      icon('two_boxes_mini', 'two_boxes_mini', '2628:7'),
      icon('documents', 'documents', '2638:52'),
      icon('lane', 'lane', '2899:37'),
      icon('vibrate', 'vibrate', '2924:479'),
      icon('volume', 'volume', '2924:484'),
      icon('lightning', 'lightning', '2925:501'),
      icon('type', 'type', '2926:512'),
      icon('palette', 'palette', '2927:517'),
      icon('note', 'note', '2929:566'),
      icon('speed_bump', 'speed_bump', '2940:37'),
      icon('ic_notification', 'ic_notification', '2955:31'),
      icon('shield_with_tick', 'shield_with_tick', '2971:37'),
      icon('volume_mute', 'volume_mute', '2971:46'),
      icon('car_front', 'car_front', '3012:38'),
      icon('rouble', 'rouble', '3038:45'),
      icon('exclaimation_mark', 'exclaimation_mark', '3042:50'),
      icon('parking', 'parking', '3055:682'),
      icon('parking_outline', 'parking_outline', '3073:28'),
      icon('handicap', 'handicap', '3076:39'),
      icon('taxi_sign', 'taxi_sign', '3077:50'),
      icon('wc', 'wc', '3084:56'),
      icon('cafe', 'cafe', '3092:23'),
      icon('driver_license', 'driver_license', '3105:31'),
      icon('rouble_crossed', 'rouble_crossed', '3111:24'),
      icon('rouble_round_crossed', 'rouble_round_crossed', '3126:30'),
      icon('washer_fluid', 'washer_fluid', '3218:24'),
    ],
  },
  {
    id: 'controls',
    title: 'Controls',
    items: [
      icon('arrow_up_round', 'arrow_up_round', '0:537'),
      icon('arrow_right_round', 'arrow_right_round', '0:449'),
      icon('arrow_down_round', 'arrow_down_round', '0:424'),
      icon('arrow_left_round', 'arrow_left_round', '0:443'),
      icon('plus_round', 'plus_round', '0:418'),
      icon('close_round', 'close_round', '0:222'),
      icon('check_round', 'check_round', '697:939'),
      icon('attention_round', 'attention_round', '0:150'),
      icon('help_round', 'help_round', '0:322'),
      icon('edit_round', 'edit_round', '871:986'),
      icon('arrow_up', 'arrow_up', '736:932'),
      icon('arrow_right', 'arrow_right', '736:933'),
      icon('arrow_down', 'arrow_down', '736:934'),
      icon('arrow_left', 'arrow_left', '0:146'),
      icon('plus', 'plus', '0:414'),
      icon('minus', 'minus', '0:356'),
      icon('close', 'close', '0:218'),
      icon('check', 'check', '0:214'),
      icon('chevron_up', 'chevron_up', '210:27'),
      icon('chevron_right', 'chevron_right', '0:473'),
      icon('chevron_down', 'chevron_down', '0:272'),
      icon('chevron_left', 'chevron_left', '736:937'),
      icon('chevron_up_mini', 'chevron_up_mini', '3374:47'),
      icon('chevron_right_mini', 'chevron_right_mini', '697:929'),
      icon('chevron_down_mini', 'chevron_down_mini', '3374:45'),
      icon('chevron_left_mini', 'chevron_left_mini', '3374:43'),
      icon('collapse', 'collapse', '2234:11'),
      icon('expand', 'expand', '2234:10'),
      icon('refresh', 'refresh', '0:430'),
      icon('play', 'play', '96:134'),
      icon('pause', 'pause', '96:133'),
      icon('download', 'download', '2965:60'),
      icon('transaction', 'transaction', '0:531'),
    ],
  },
  {
    id: 'operations',
    title: 'Operations',
    items: [
      icon('plane', 'plane', '0:410'),
      icon('point_railway', 'point/railway', '448:34'),
      icon('point_city', 'point/city', '448:36'),
      icon('animals_in_the_car', 'animals_in_the_car', '0:137'),
      icon('achievement', 'achievement', '0:130'),
      icon('baby_chair', 'baby_chair', '0:157'),
      icon('barrier', 'barrier', '0:172'),
      icon('bonus', 'bonus', '0:180'),
      icon('bonus_user', 'bonus_user', '0:188'),
      icon('busline', 'busline', '0:196'),
      icon('cash', 'cash', '0:204'),
      icon('coefficient', 'coefficient', '0:228'),
      icon('credit_card', 'credit_card', '0:235'),
      icon('door', 'door', '0:252'),
      icon('falcon', 'falcon', '0:276'),
      icon('fraud', 'fraud', '0:301'),
      icon('gas', 'gas', '0:316'),
      icon('message', 'message', '0:341'),
      icon('no_smoking', 'no smoking', '0:366'),
      icon('pin', 'pin', '0:402'),
      icon('delivery_from_door', 'delivery_from_door', '249:22'),
      icon('sober', 'sober', '0:477'),
      icon('delivery', 'delivery', '451:15'),
      icon('ticket', 'ticket', '0:511'),
      icon('tips', 'tips', '0:527'),
      icon('wallet', 'wallet', '466:51'),
      icon('refund', 'refund', '0:434'),
      icon('fast_pick_up', 'fast_pick_up', '397:19'),
      icon('house', 'house', '110:5'),
      icon('motivation_round', 'motivation_round', '145:15'),
      icon('tree', 'tree', '793:3'),
      icon('restaurant', 'restaurant', '1835:5'),
      icon('skier', 'skier', '1931:9'),
      icon('heavy', 'heavy', '2365:9'),
      icon('water_drop', 'water_drop', '2861:34'),
    ],
  },
];

export function iconAssetPath(sectionId: string, iconId: string): string {
  return `/icons/${sectionId}/${iconId}.svg`;
}
